#ifndef __DATALOG__H
#define __DATALOG__H

#define DATALOG_ENABLED

typedef enum
{
	DATALOG_MAIN_THREAD,
	DATALOG_IMU_THREAD,
	DATALOG_MOTOR_THREAD
} DATALOG_THREAD_t;

typedef enum
{
	DATALOG_ACCEL_UNCAL_RECORD,
	DATALOG_ACCEL_CAL_RECORD,
	DATALOG_GYRO_UNCAL_RECORD,
	DATALOG_GYRO_CAL_RECORD,
	DATALOG_QUAT_RECORD,
	DATALOG_EULER_ANGLES_RECORD,
	DATALOG_PID_KP_RECORD,
	DATALOG_PID_KI_RECORD,
	DATALOG_PID_KD_RECORD,
	DATALOG_ROLL,
	DATALOG_WHEEL_SPEED,
	DATALOG_SPEED_CONTROL_SP,
	DATALOG_MOTOR_RECORD
} DATALOG_RECORD_t;

void datalog_trigger();
void datalog_record(DATALOG_RECORD_t record_type, float *record, int32_t *recordi);

#endif
